//
//  BubbleView.swift
//  Digin
//
//  Created by jinho jeong on 2021/05/01.
//

import UIKit

class BubbleView: UIView {

    // Only override draw() if you perform custom drawing.
    // An empty implementation adversely affects performance during animation.
    override func draw(_ rect: CGRect) {
        // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
        // http://www.paintcodeapp.com

        //// Color Declarations
        let fillColor = UIColor(red: 0.969, green: 0.969, blue: 0.969, alpha: 1.000)
        let fillColor2 = UIColor(red: 0.322, green: 0.000, blue: 1.000, alpha: 1.000)

        //// imgBubbleStart.svg Group
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 15.77, y: 1))
        bezierPath.addCurve(to: CGPoint(x: 1, y: 15.77), controlPoint1: CGPoint(x: 7.61, y: 1), controlPoint2: CGPoint(x: 1, y: 7.61))
        bezierPath.addCurve(to: CGPoint(x: 15.77, y: 30.54), controlPoint1: CGPoint(x: 1, y: 23.92), controlPoint2: CGPoint(x: 7.61, y: 30.54))
        bezierPath.addLine(to: CGPoint(x: 21.13, y: 30.54))
        bezierPath.addLine(to: CGPoint(x: 27.37, y: 36.43))
        bezierPath.addCurve(to: CGPoint(x: 30.25, y: 36.4), controlPoint1: CGPoint(x: 28.17, y: 37.19), controlPoint2: CGPoint(x: 29.46, y: 37.18))
        bezierPath.addLine(to: CGPoint(x: 36.21, y: 30.53))
        bezierPath.addLine(to: CGPoint(x: 73.23, y: 30.53))
        bezierPath.addCurve(to: CGPoint(x: 88, y: 15.77), controlPoint1: CGPoint(x: 81.39, y: 30.53), controlPoint2: CGPoint(x: 88, y: 23.92))
        bezierPath.addCurve(to: CGPoint(x: 73.23, y: 1), controlPoint1: CGPoint(x: 88, y: 7.61), controlPoint2: CGPoint(x: 81.39, y: 1))
        bezierPath.addLine(to: CGPoint(x: 15.77, y: 1))
        bezierPath.close()
        fillColor.setFill()
        bezierPath.fill()

        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 21.13, y: 30.53))
        bezier2Path.addLine(to: CGPoint(x: 21.81, y: 29.81))
        bezier2Path.addLine(to: CGPoint(x: 21.52, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 21.13, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 21.13, y: 30.53))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 27.37, y: 36.43))
        bezier2Path.addLine(to: CGPoint(x: 28.06, y: 35.71))
        bezier2Path.addLine(to: CGPoint(x: 27.37, y: 36.43))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 30.25, y: 36.4))
        bezier2Path.addLine(to: CGPoint(x: 30.95, y: 37.12))
        bezier2Path.addLine(to: CGPoint(x: 30.25, y: 36.4))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 36.21, y: 30.53))
        bezier2Path.addLine(to: CGPoint(x: 36.21, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 35.8, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 35.51, y: 29.82))
        bezier2Path.addLine(to: CGPoint(x: 36.21, y: 30.53))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 15.77, y: 0))
        bezier2Path.addCurve(to: CGPoint(x: 0, y: 15.77), controlPoint1: CGPoint(x: 7.06, y: 0), controlPoint2: CGPoint(x: 0, y: 7.06))
        bezier2Path.addLine(to: CGPoint(x: 2, y: 15.77))
        bezier2Path.addCurve(to: CGPoint(x: 15.77, y: 2), controlPoint1: CGPoint(x: 2, y: 8.16), controlPoint2: CGPoint(x: 8.16, y: 2))
        bezier2Path.addLine(to: CGPoint(x: 15.77, y: 0))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 0, y: 15.77))
        bezier2Path.addCurve(to: CGPoint(x: 15.77, y: 31.53), controlPoint1: CGPoint(x: 0, y: 24.48), controlPoint2: CGPoint(x: 7.06, y: 31.53))
        bezier2Path.addLine(to: CGPoint(x: 15.77, y: 29.53))
        bezier2Path.addCurve(to: CGPoint(x: 2, y: 15.77), controlPoint1: CGPoint(x: 8.16, y: 29.53), controlPoint2: CGPoint(x: 2, y: 23.37))
        bezier2Path.addLine(to: CGPoint(x: 0, y: 15.77))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 15.77, y: 31.53))
        bezier2Path.addLine(to: CGPoint(x: 21.13, y: 31.53))
        bezier2Path.addLine(to: CGPoint(x: 21.13, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 15.77, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 15.77, y: 31.53))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 20.44, y: 31.26))
        bezier2Path.addLine(to: CGPoint(x: 26.68, y: 37.16))
        bezier2Path.addLine(to: CGPoint(x: 28.06, y: 35.71))
        bezier2Path.addLine(to: CGPoint(x: 21.81, y: 29.81))
        bezier2Path.addLine(to: CGPoint(x: 20.44, y: 31.26))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 26.68, y: 37.16))
        bezier2Path.addCurve(to: CGPoint(x: 30.95, y: 37.12), controlPoint1: CGPoint(x: 27.88, y: 38.29), controlPoint2: CGPoint(x: 29.78, y: 38.27))
        bezier2Path.addLine(to: CGPoint(x: 29.55, y: 35.69))
        bezier2Path.addCurve(to: CGPoint(x: 28.06, y: 35.71), controlPoint1: CGPoint(x: 29.14, y: 36.09), controlPoint2: CGPoint(x: 28.47, y: 36.1))
        bezier2Path.addLine(to: CGPoint(x: 26.68, y: 37.16))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 30.95, y: 37.12))
        bezier2Path.addLine(to: CGPoint(x: 36.91, y: 31.25))
        bezier2Path.addLine(to: CGPoint(x: 35.51, y: 29.82))
        bezier2Path.addLine(to: CGPoint(x: 29.55, y: 35.69))
        bezier2Path.addLine(to: CGPoint(x: 30.95, y: 37.12))
        bezier2Path.addLine(to: CGPoint(x: 30.95, y: 37.12))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 36.21, y: 31.53))
        bezier2Path.addLine(to: CGPoint(x: 93.23, y: 31.53)) //
        bezier2Path.addLine(to: CGPoint(x: 93.23, y: 29.53)) //
        bezier2Path.addLine(to: CGPoint(x: 36.21, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 36.21, y: 31.53))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 93.23, y: 31.53))
        bezier2Path.addCurve(to: CGPoint(x: 89, y: 15.77), controlPoint1: CGPoint(x: 81.94, y: 31.53), controlPoint2: CGPoint(x: 89, y: 24.48))
        bezier2Path.addLine(to: CGPoint(x: 87, y: 15.77))
        bezier2Path.addCurve(to: CGPoint(x: 73.23, y: 29.53), controlPoint1: CGPoint(x: 87, y: 23.37), controlPoint2: CGPoint(x: 80.84, y: 29.53))
        bezier2Path.addLine(to: CGPoint(x: 93.23, y: 31.53))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 89, y: 15.77))
        bezier2Path.addCurve(to: CGPoint(x: 73.23, y: 0), controlPoint1: CGPoint(x: 89, y: 7.06), controlPoint2: CGPoint(x: 81.94, y: 0))
        bezier2Path.addLine(to: CGPoint(x: 93.23, y: 2))
        bezier2Path.addCurve(to: CGPoint(x: 87, y: 15.77), controlPoint1: CGPoint(x: 80.84, y: 2), controlPoint2: CGPoint(x: 87, y: 8.16))
        bezier2Path.addLine(to: CGPoint(x: 89, y: 15.77))
        bezier2Path.close()
        bezier2Path.move(to: CGPoint(x: 93.23, y: 0))
        bezier2Path.addLine(to: CGPoint(x: 15.77, y: 0))
        bezier2Path.addLine(to: CGPoint(x: 15.77, y: 2))
        bezier2Path.addLine(to: CGPoint(x: 73.23, y: 2))
        bezier2Path.addLine(to: CGPoint(x: 73.23, y: 0))
        bezier2Path.close()
        fillColor2.setFill()
        bezier2Path.fill()

    }

}
